config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"

  devise_for :user, path: "devises", controllers: {
    passwords: "devises/passwords",
    registrations: "devises/registrations",
    sessions: "devises/sessions",
  }, skip: [:sessions, :registrations]
  as :user do
    get "login", to: "devises/sessions#new", as: :new_user_session
    post "login", to: "devises/sessions#create", as: :user_session
    get "signup", to: "devises/registrations#new", as: :new_user_registration
    post "signup", to: "devises/registrations#create", as: :user_registration
    put "/signup", to: "devises/users#update"
    get "edit", to: "devises/users#edit", as: :edit_user_registration
    delete "logout", to: "devises/sessions#destroy", as: :destroy_user_session
  end

  resources :set_language, only: :index

  resources :users, only: %i(show edit update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  acts_as_paranoid

  has_many :subject_departments, dependent: :destroy
  has_many :major_departments, dependent: :destroy
  has_many :registers, dependent: :destroy
  has_many :subjects, through: :subject_departments
  has_many :majors, through: :major_departments
  has_many :schools, through: :majors
  has_many :results, through: :subjects
  has_many :users, through: :results

  serialize :school_id, Array
end

app/models/major.rb
class Major < ApplicationRecord::Base
  acts_as_paranoid

  belongs_to :school
  has_many :major_departments, dependent: :destroy
  has_many :targets, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :registers, dependent: :destroy
  has_many :users, through: :registers
  has_many :departments. through: :major_departments
  has_many :subjects_departmants, through: :departments
  has_many :subjects, through: :subjects_departmants
end

app/models/major_department.rb
class MajorDepartment < ApplicationRecord::Base
  acts_as_paranoid

  belongs_to :major
  belongs_to :departments
  has_one :school, through: :major
  has_many :subject_departments. through: :departments
  has_many :subjects, through: :subject_departments
  has_many :targets, through: :major
end

app/models/note.rb
class Note < ApplicationRecord
  acts_as_paranoid
end

app/models/notification.rb
class Notification < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  belongs_to :event, polymorphic: true

  serialize :user_read, Array
  serialize :user_readed, Array
end

app/models/register.rb
class Register < ApplicationRecord
  acts_as_paranoid

  belongs_to :major
  belongs_to :user
  belongs_to :department
  has_one :school, through: :major
  has_many :subject_departments, through: :department
  has_many :subjects, through: :subject_departments
  has_many :results, through: :subjects
end

app/models/remarking.rb
class Remarking < ApplicationRecord
  acts_as_paranoid

  belongs_to :result
  belongs_to :school
  has_one :user, through: :result
  has_one :subject, through: :result
end

app/models/result.rb
class Result < ApplicationRecord
  acts_as_paranoid

  belongs_to :subject
  belongs_to :user
  has_many :remarkings, dependent: :destroy
  has_many :subject_departments, through: :subject
  has_many :department, through: :subject_departments
  has_many :registers, through: :user
  has_many :majors, through: :registers
  has_many :schools, through: :majors
end

app/models/review.rb
class Review < ApplicationRecord
  acts_as_paranoid

  belongs_to :major
end

app/models/school.rb
class School < ApplicationRecord
  acts_as_paranoid

  has_many :majors, dependent: :destroy
  has_many :remarkings, dependent: :destroy
  has_many :teacher, dependent: :destroy
  has_many :registers, through: :majors
  has_many :reviews, through: :majors
  has_many :users, through: :registers
  has_many :major_departments, through: :majors
  has_many :departments, through: :major_departments
  has_many :subject_departments, through: :departments
  has_many :subjects, through: :subject_departments
end

app/models/subject_department.rb
class SubjectDepartment < ApplicationRecord
  acts_as_paranoid

  belongs_to :subjects, dependent: :destroy
  belongs_to :department, dependent: :destroy
  has_many :results, through: :subjects
  has_many :major_department, through: :department
end

app/models/subjects.rb
class Subjects < ApplicationRecord
  acts_as_paranoid

  has_many :subject_departments, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :departments, through: :subject_departments
  has_many :users, through: :results
  has_many :major_departments, through: :departments
  has_many :majors, through: :major_departments
  has_many :schools, through: :majors
end

app/models/target.rb
class Target < ApplicationRecord
  acts_as_paranoid

  belongs_to :major
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  acts_as_paranoid

  belongs_to :school
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  acts_as_paranoid

  has_many :results, dependent: :destroy
  has_many :registers, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :remarkings, through: :results
  has_many :majors, through: :registers
  has_many :schools, through: :majors
  has_many :subjects, through: :results
  has_many :departments, through: :results
  has_many :major_departments, through: :majors
  has_many :departments, through: :major_departments

  validates :name, presence: true
  validates :email, presence: true
  validates :people_id, presence: true
  validates :identification_number, presence: true

  enum role: %i(student teacher admin)
  enum sex: %i(unknown male female)
  enum level: %i(university college Intermediate)

  mount_uploader :avatar, PictureUploader

  def picture_size
    if avatar.size > 5.megabytes
      errors.add :avatar, t("less_than_5")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end
end

app/controllers/set_language_controller.rb
class SetLanguageController < ApplicationController

  def index
    if I18n.available_locales.include? params[:locale].to_sym
      I18n.locale = params[:locale].to_sym
    else
      I18n.locale = :en
    end
    set_session_and_redirect
  end

  private

  def set_session_and_redirect
    session[:locale] = I18n.locale
    redirect_back fallback_location: root_path
    rescue ActionController::RedirectBackError
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user, only: %i(show edit update)

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @user.update_attributes user_params
        format.js{@success = t "update_success"}
      else
        format.js{@errors = t "update_failure"}
      end
    end
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "nil_user"
    redirect_to root_url
  end

  def load_user_ajax
    @user = User.find_by id: params[:id]
    return if @user
    @error = t "nil_user"
  end

  def user_params
    params[:user][:sex] = params[:user][:sex].to_i if params[:user]
    params.require(:user).permit :birthday, :address, :phone, :avatar, :sex,
      :religion, :nation, :nationality
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title page_title = ""
    base_title = I18n.t("app")
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def resource
    @resource ||= User.new
  end

  def resource_name
    :user
  end
end

app/views/devise_custom/_form_forgot_password.html.erb
<%= form_for resource, as: resource_name, url: password_path(resource_name),
  html: {method: :post, id: "form-forgot-password"} do |f| %>
  <div class="form-group forgot-error display-none">
    <div class="col-xs-12">
      <p class="color-red text-center"></p>
      <span class="close-error">&times;</span>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
        <%= f.email_field :email, autofocus: true, class: "form-control input-lg",
          id: "forgot-email", placeholder: t("email") %>
      </div>
    </div>
  </div>
  <div class="form-group text-center p-15">
    <%= f.button :submit, class: "btn btn-sm btn-primary" do %>
      <%= t "send" %>
    <% end %>
  </div>
  <div class="form-group text-center p-15">
    <a href="javascript:void(0)" class="link-forgot-login">
    <small><%= t "login" %></small></a>
  </div>
<% end %>

app/views/devise_custom/_form_login.html.erb
<%= form_for resource, as: resource_name, url: user_session_path(resource_name),
  html: {id: "form-login"} do |f| %>
  <div class="form-group login-error display-none">
    <div class="col-xs-12">
      <p class="color-red text-center"></p>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
        <%= f.email_field :email, autofocus: true, class: "form-control input-lg",
          placeholder: t("email"), id: "login-email" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-key"></i></span>
        <%= f.password_field :password,class: "form-control input-lg",
          placeholder: t("password"), id: "login-password"  %>
      </div>
    </div>
  </div>

  <div class="form-group form-actions remember-login p-15">
    <div class="pull-left">
      <%= f.label :remember_me, class: "checkbox inline remember_me" do %>
        <label class="switch switch-primary" data-toggle="tooltip">
          <%= f.check_box :remember_me,id: "login-remember-me" %>
          <span></span>
        </label>
      <% end %>
    </div>
    <div class="pull-right">
      <%= f.button :submit, class: "btn btn-sm btn-primary" do %>
        <%= t "login" %>
      <% end %>
    </div>
  </div>

  <div class="form-group p-15">
    <div class="text-center">
      <%= link_to "javascript:void(0)", class: "link-forgot-password" do %>
        <p><%= t "forgot" %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/devise_custom/_login.html.erb
<%= stylesheet_link_tag "login" %>
<div id="modal-login" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div id="login-ajax">
        <div class="login-title text-center">
          <i class="close-form-login" data-dismiss="modal">&times;</i>
          <h1>
            <i class="gi gi-flash"></i>
            <strong><%= t "app" %></strong><br>
            <small>
              <%= t "please" %>
              <strong><%= t "login" %></strong>
            </small>
          </h1>
        </div>
        <div class="block">
          <div class="form-horizontal form-bordered form-control-borderless form-login">
            <%= render "devise_custom/form_login" %>
          </div>
          <div class="form-horizontal form-bordered form-control-borderless form-fogot display-none">
            <%= render "devise_custom/form_forgot_password" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_user_footer.html.erb
<%= stylesheet_link_tag "user_footer" %>
<div id="footer">
  <div class="container">
    <div class="row">
      <h3 class="footertext">About Us:</h3>
      <br>
        <div class="col-md-4">
          <center>
            <img src="http://oi60.tinypic.com/w8lycl.jpg" class="img-circle" alt="the-brains">
            <br>
            <h4 class="footertext">Programmer</h4>
            <p class="footertext">You can thank all the crazy programming here to this guy.<br>
          </center>
        </div>
        <div class="col-md-4">
          <center>
            <img src="http://oi60.tinypic.com/2z7enpc.jpg" class="img-circle" alt="...">
            <br>
            <h4 class="footertext">Artist</h4>
            <p class="footertext">All the images here are hand drawn by this man.<br>
          </center>
        </div>
        <div class="col-md-4">
          <center>
            <img src="http://oi61.tinypic.com/307n6ux.jpg" class="img-circle" alt="...">
            <br>
            <h4 class="footertext">Designer</h4>
            <p class="footertext">This pretty site and the copy it holds are all thanks to this guy.<br>
          </center>
        </div>
      </div>
      <div class="row copyright">
      <p><center><a href="#">Contact Stuff Here</a> <p class="footertext">Copyright 2014</p></center></p>
    </div>
  </div>
</div>

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-user m-0">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <li class="active">
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <span class="glyphicon glyphicon-search"></span> Search
        <% end %>
      </li>

      <li>
        <%= link_to "http://www.udn.vn/" do %>
          <span class="glyphicon glyphicon-question-sign"></span> Help
        <% end %>
      </li>
      <li>
        <%= link_to "http://www.udn.vn/" do %>
          <span class="glyphicon glyphicon-book"></span> Guides
       <% end %>
      </li>
      <li>
        <%= link_to "http://www.udn.vn/" do %>
          <span class="glyphicon"></span> Library Information
        <% end %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right site-nav">
      <% if user_signed_in? %>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span> User
          <span class="caret"></span></a>
          <ul class="dropdown-menu min-w-180">
            <li>
              <%= link_to user_path(current_user) do %>
                <%= t("profile") %><i class="fa fa-address-book pull-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_url(current_user) do %>
                <%= t("change_pass") %><i class="fa fa-pencil-square-o pull-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t("logout") %><i class="fa fa-sign-out pull-right"></i>
              <% end %>
            </li>
          </ul>
      <% else %>
        <li>
          <%= link_to "javascript:void(0)", class: "btn-login-user" do %>
            <i class="fa fa-sign-in"></i> <%= t("login") %>
          <% end %>
        </li>
      <% end %>
      <%= render "shared/language_local" %>
    </ul>
  </div>
</nav>
<%= render "devise_custom/login" %>
<%= javascript_include_tag "login" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag "logo.jpg" %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="page-container">
      <%= render "layouts/user_header" %>
      <div id="content-body-custom">
        <div class="row">
          <center>
            <div class="w-1200">
              <% flash.each do |message_type, message| %>
                <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
              <% end %>
            </div>
          </center>
          <div class="page-content">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>

  <footer class="site-footer padding-10-0 footer-custom">
    <%= render "layouts/user_footer" %>
  </footer>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error_messages" %> <%= pluralize(object.errors.size, t("error")) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% [:notice, :error, :alert, :success].each do |level| %>
  <% unless flash[level].blank? %>
    <div id="flash-message" class="alert <%= flash_class level %> flash-message">
      <%= sanitize flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/shared/_language_local.html.erb
<li class="dropdown">
  <% if I18n.locale == Settings.language.vi.to_sym %>
    <%= link_to "javascript:void(0)", data: {toggle: "dropdown"},
      class: "dropdown-toggle lang-sel-sel icl-vi" do %>
      <%= image_tag "vi.png", height: 15, witdh: 25 %>
    <% end %>
  <% else %>
    <%= link_to "javascript:void(0)", data: {toggle: "dropdown"},
      class: "dropdown-toggle lang-sel-sel icl-vi" do %>
      <%= image_tag "en.png", height: 15, witdh: 25 %>
    <% end %>
  <% end %>
  <ul class="dropdown-menu text-center">
    <li>
      <%= link_to set_language_index_path(locale: Settings.language.en) do %>
        <%= image_tag "en.png", height: 15, witdh: 25 %>
        <%= t "english" %>
      <% end %>
    </li>
    <li>
      <%= link_to set_language_index_path(locale: Settings.language.vi) do %>
        <%= image_tag "vi.png", height: 15, witdh: 25 %>
        <%= t "viet_nam" %>
      <% end %>
    </li>
  </ul>
</li>